# Generated by Django 4.0.4 on 2022-06-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='body',
            new_name='bio',
        ),
    ]
