# Generated by Django 4.0.4 on 2022-06-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_body_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_a_proffessional_account',
            field=models.BooleanField(default=False),
        ),
    ]
