# Generated by Django 4.0.4 on 2022-06-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_last_name_profile_subname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='family_name',
        ),
    ]
