# Generated by Django 4.0.4 on 2034-06-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of recipe')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description of recipe')),
                ('nbre_of_plates', models.IntegerField(max_length=255, verbose_name='Number of plates of recipe')),
                ('time_preparation', models.IntegerField(max_length=255, verbose_name='Time of preparation of recipe')),
                ('time_cuisson', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Time of cuisson of recipe')),
                ('status', models.CharField(default='public', max_length=255, verbose_name='Status of recipe')),
                ('preparation_etape', models.TextField()),
                ('cuisson_etape', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
