# Generated by Django 4.0.4 on 2034-06-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='nbre_of_plates',
            field=models.IntegerField(verbose_name='Number of plates of recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_cuisson',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time of cuisson of recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_preparation',
            field=models.IntegerField(verbose_name='Time of preparation of recipe'),
        ),
    ]
