# Generated by Django 4.0.4 on 2022-06-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created',
            new_name='created_at',
        ),
    ]
